import Head from 'next/head';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col w-full h-screen items-center justify-center'>
        <h1>Test tailwind css</h1>
      </main>
    </div>
  );
}
